### ISSUE TITLE
Olá, tem tem um preview dele?

### ISSUE THREAD

**Issue by sebastianjnuwu** [Rick504/GameRPG_One#6]
tipo a URL

**Comment by Rick504** [comment]
Boa tarde Sebastin, esse projeto não está em produção, somente rodando
localmente usando docker, ele sobe toda aplicação em um container do docker
localmente.

Em qua., 18 de jan. de 2023 às 09:00, SEBASTIAN JN ***@***.***>
escreveu:

**Comment by sebastianjnuwu** [comment]
Ok,
